FROM python:3.11-buster
ENV PYTHONUNBUFFERED=1

RUN mkdir /code
WORKDIR /code

COPY ./requirements/base.txt /code/
COPY ./requirements/production.txt /code/

RUN pip install --upgrade pip
RUN pip install -r production.txt

COPY . /code/

EXPOSE 5000
STOPSIGNAL SIGINT
