# docker-compose -f docker-compose-test.yml up --build
version: "3.8"

services:
  postgres_db:
    image: postgres:14
    container_name: test-db
    restart: unless-stopped
    volumes:
      - postgres_data_test:/var/lib/postgresql/data/:/var/lib/postgresql/data/
    environment: 
      - POSTGRES_DB=admin 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres  
    healthcheck:
      test: pg_isready -d admin -U postgres 
      interval: 2s
      retries: 10
    
  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: test-container
    command: pytest
    volumes:
      - .:/code
    env_file:
      - ./.env
    depends_on:
      postgres_db:
        condition: service_healthy

volumes:
  postgres_data_test:
