FROM python:3.11-buster

#output is immediately flushed and shown in the console 
ENV PYTHONUNBUFFERED=1

# create code directory
RUN mkdir /code
WORKDIR /code

# copy just requirement files and install before rest of code to avoid having to
# reinstall packages during build every time code changes
COPY ./requirements.txt /code/

# upgrade pip and install requirements
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# copy code files
COPY . /code/

EXPOSE 5000
STOPSIGNAL SIGINT